### ISSUE TITLE
你这个程序有加密吗？

### ISSUE THREAD

**Issue by luckypoem** [bit-ranger/bit-tunnel#3]
我看了2边的参数，没看见关于加密的参数

**Comment by bit-ranger** [comment]
有加密
https://github.com/bit-ranger/bit-tunnel/blob/95b5a66e14ec82013bedfcbcfcfc9223a04b7227/common/src/cryptor.rs#L16

密钥参数名为k
https://github.com/bit-ranger/bit-tunnel/blob/95b5a66e14ec82013bedfcbcfcfc9223a04b7227/client/src/bin/client.rs#L171
